inherit_from: "configs/ERP/360VO/base_config.yaml"

Dataset:
  dataset_path: "datasets/360VO/seq7/"
  Calibration:
    width: 1920
    height: 960
    cube_face_size: 512
    distorted: False
  # 可选：控制处理的帧范围
  #start_frame: 2500      # 起始帧索引（从0开始），不设置则从第0帧开始
  end_frame: 1200      # 结束帧索引（不包含），不设置则处理到数据集末尾


